; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATtiny3224]
platform = atmelmegaavr
board = ATtiny3224
framework = arduino
upload_protocol = serialupdi
lib_deps = adafruit/Adafruit NeoPixel@^1.15.2
build_src_filter = +<*> -<main_native.cpp> -<native/>

[env:native]
platform = native
build_flags = -DNATIVE -std=c++17 -Isrc
build_src_filter = +<*> -<main.cpp> -<at/>

[env:test_native]
platform = native
build_flags = -DNATIVE -std=c++17 -Isrc
build_src_filter = +<*> -<main.cpp> -<main_native.cpp> -<at/>
