#!/usr/bin/env python3
"""
Assign (or look up) this board's Row Bus address from its RP2350 CHIPID.

The RP2350 has a genuine 64-bit CHIPID burned into OTP at the factory
(rows CHIPID0-CHIPID3), readable via `picotool otp get` while the board is
in BOOTSEL mode - before any firmware is flashed. This script reads that
ID, looks it up in tools/row-address-map.json (the durable fleet roster,
committed to git), and either returns the address already on file for this
board or assigns the next free address (0x00-0x07 - the wire protocol's
actual range, not 1-8) and persists it.

It then (re)writes src/row/include/row_address_generated.h with
`#define MY_ROW_ADDR <n>` for main.cpp to consume.

Usage:
  python3 tools/assign_row_address.py

Requires exactly one RP2350 board connected in BOOTSEL mode.
"""

import json
import os
import re
import shutil
import subprocess
import sys

_HERE      = os.path.dirname(os.path.abspath(__file__))
_PROJECT   = os.path.abspath(os.path.join(_HERE, '..'))
MAP_PATH   = os.path.join(_HERE, 'row-address-map.json')
HEADER_PATH = os.path.join(_PROJECT, 'include', 'row_address_generated.h')

MAX_ADDR = 7  # row addresses are 0x00-0x07 (8 rows); 0xFF is reserved for broadcast

CHIPID_ROWS = ['CHIPID0', 'CHIPID1', 'CHIPID2', 'CHIPID3']

# Matches e.g. "CHIPID0: 0x1a2b" or "CHIPID0 (0xf00000): 0x1a2b" - a row's
# own address/offset can appear as a hex token *before* its actual value
# (e.g. in parens), so this takes the LAST hex token on the line naming
# that row, not the first. picotool's exact `otp get` formatting hasn't
# been confirmed against real hardware (no device was available while
# writing this script) - if this ever fails to find all 4 rows, the raw
# output is printed so the format can be fixed here.
_HEX_TOKEN_RE = re.compile(r'0x[0-9a-fA-F]+')
_ROW_NAME_RE = {row: re.compile(rf'\b{row}\b') for row in CHIPID_ROWS}


def _find_row_value(output: str, row: str) -> int | None:
    name_re = _ROW_NAME_RE[row]
    for line in output.splitlines():
        if not name_re.search(line):
            continue
        tokens = _HEX_TOKEN_RE.findall(line)
        if tokens:
            return int(tokens[-1], 16) & 0xFFFF
    return None


def find_picotool() -> str:
    found = shutil.which('picotool')
    if found:
        return found
    import glob
    candidates = glob.glob(os.path.expanduser('~/.platformio/packages/tool-picotool*/picotool'))
    if candidates:
        return candidates[0]
    print('ERROR: picotool not found on PATH or under ~/.platformio/packages/', file=sys.stderr)
    sys.exit(1)


def read_chip_id() -> str:
    """Returns the 64-bit CHIPID as a 16-hex-char string (no 0x prefix)."""
    picotool = find_picotool()
    result = subprocess.run(
        [picotool, 'otp', 'get', '-n'] + CHIPID_ROWS,
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print('ERROR: picotool otp get failed - is the board in BOOTSEL mode?', file=sys.stderr)
        print(result.stdout, file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)

    values = {}
    for row in CHIPID_ROWS:
        value = _find_row_value(result.stdout, row)
        if value is None:
            print(f'ERROR: could not find {row} in picotool output - format may have '
                  f'changed; update tools/assign_row_address.py\'s parser.', file=sys.stderr)
            print('--- picotool output ---', file=sys.stderr)
            print(result.stdout, file=sys.stderr)
            sys.exit(1)
        values[row] = value

    # CHIPID0 = bits 15:0, CHIPID1 = bits 31:16, CHIPID2 = bits 47:32, CHIPID3 = bits 63:48
    chip_id = (values['CHIPID3'] << 48) | (values['CHIPID2'] << 32) \
            | (values['CHIPID1'] << 16) | values['CHIPID0']
    return f'{chip_id:016x}'


def load_map() -> dict:
    if not os.path.isfile(MAP_PATH):
        return {}
    with open(MAP_PATH) as f:
        return json.load(f)


def save_map(mapping: dict):
    with open(MAP_PATH, 'w') as f:
        json.dump(mapping, f, indent=2, sort_keys=True)
        f.write('\n')


def assign_or_lookup(chip_id: str, mapping: dict) -> tuple[int, bool]:
    """Returns (address, is_new)."""
    if chip_id in mapping:
        return mapping[chip_id], False

    used = set(mapping.values())
    for addr in range(MAX_ADDR + 1):
        if addr not in used:
            mapping[chip_id] = addr
            return addr, True

    print(f'ERROR: all {MAX_ADDR + 1} row addresses are already assigned in {MAP_PATH} - '
          f'no free address for chip {chip_id}', file=sys.stderr)
    sys.exit(1)


def write_header(addr: int):
    with open(HEADER_PATH, 'w') as f:
        f.write(
            '#pragma once\n'
            '// Auto-generated by tools/assign_row_address.py - do not edit by hand.\n'
            '// Maps this board\'s RP2350 CHIPID to its Row Bus address (0x00-0x07).\n'
            f'#define MY_ROW_ADDR 0x{addr:02X}\n'
        )


def main() -> int:
    chip_id = read_chip_id()
    mapping = load_map()
    addr, is_new = assign_or_lookup(chip_id, mapping)

    if is_new:
        save_map(mapping)
        print(f'chip {chip_id}: assigned NEW row address 0x{addr:02X}')
    else:
        print(f'chip {chip_id}: row address 0x{addr:02X} (already on file)')

    write_header(addr)
    print(f'wrote {HEADER_PATH}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
